// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Trading.Infrastructure.Persistence;

#nullable disable

namespace Trading.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TradingDbContext))]
    [Migration("20260923042928_M38DurableAutomationAuthorization")]
    partial class M38DurableAutomationAuthorization
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Trading.Domain.Execution.ControlledAutomationAuthorization", b =>
                {
                    b.Property<Guid>("AutomationDecisionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ActionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActionReference")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("AutomationSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)")
                        .IsFixedLength();

                    b.Property<int>("ConsumedActions")
                        .HasColumnType("int");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("EvaluatedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<DateTime>("FirstConsumedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<DateTime>("LastConsumedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<int>("MaximumAuthorizedActions")
                        .HasColumnType("int");

                    b.Property<Guid>("RelatedLiveOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StrategyId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("AutomationDecisionId");

                    b.HasIndex("ActionId")
                        .IsUnique();

                    b.HasIndex("AutomationSha256")
                        .IsUnique();

                    b.HasIndex("RelatedLiveOrderId")
                        .IsUnique();

                    b.ToTable("ControlledAutomationAuthorizations", null, t =>
                        {
                            t.HasCheckConstraint("CK_ControlledAutomationAuthorizations_Actions", "[MaximumAuthorizedActions] = 1 AND [ConsumedActions] = 1");

                            t.HasCheckConstraint("CK_ControlledAutomationAuthorizations_Decision", "[Decision] = 'DirectSubmissionEligible'");

                            t.HasCheckConstraint("CK_ControlledAutomationAuthorizations_Validity", "[EvaluatedAtUtc] <= [FirstConsumedAtUtc] AND [FirstConsumedAtUtc] < [ExpiresAtUtc]");
                        });
                });

            modelBuilder.Entity("Trading.Domain.Execution.LiveOrderRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ArtifactJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArtifactSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)")
                        .IsFixedLength();

                    b.Property<string>("BrokerOrderId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<decimal>("LimitPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("PaperEvidenceSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)")
                        .IsFixedLength();

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RiskDecisionSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)")
                        .IsFixedLength();

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<decimal>("StopPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid>("StrategyCertificateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StrategyId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<decimal>("TargetPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("TradingSymbol")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("nvarchar(96)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("RequestId")
                        .IsUnique();

                    b.HasIndex("StrategyCertificateId");

                    b.ToTable("LiveOrders", null, t =>
                        {
                            t.HasCheckConstraint("CK_LiveOrders_Mode", "[Mode] IN ('SemiLive', 'DirectLive')");

                            t.HasCheckConstraint("CK_LiveOrders_Prices", "[Quantity] > 0 AND [StopPrice] > 0 AND [StopPrice] < [LimitPrice] AND [TargetPrice] > [LimitPrice]");

                            t.HasCheckConstraint("CK_LiveOrders_Status", "[Status] IN ('Proposed', 'Prepared', 'Submitted')");
                        });
                });

            modelBuilder.Entity("Trading.Domain.Execution.PaperTradingSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ArtifactJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArtifactSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)")
                        .IsFixedLength();

                    b.Property<string>("ConfigurationSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)")
                        .IsFixedLength();

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<decimal>("EndingCash")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("FilledTrades")
                        .HasColumnType("int");

                    b.Property<decimal>("InitialCash")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid>("MarketFeedCaptureId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("RealizedNetPnl")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("RejectedOrders")
                        .HasColumnType("int");

                    b.Property<Guid>("StrategyCertificateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StrategyId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("SubmittedOrders")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("MarketFeedCaptureId");

                    b.HasIndex("StrategyCertificateId", "MarketFeedCaptureId", "ConfigurationSha256")
                        .IsUnique();

                    b.ToTable("PaperTradingSessions", null, t =>
                        {
                            t.HasCheckConstraint("CK_PaperTradingSessions_Cash", "[InitialCash] > 0 AND [EndingCash] >= 0");

                            t.HasCheckConstraint("CK_PaperTradingSessions_Counts", "[SubmittedOrders] > 0 AND [FilledTrades] >= 0 AND [RejectedOrders] >= 0 AND [FilledTrades] + [RejectedOrders] = [SubmittedOrders]");
                        });
                });

            modelBuilder.Entity("Trading.Domain.MarketData.Candle", b =>
                {
                    b.Property<Guid>("InstrumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Timeframe")
                        .HasColumnType("int");

                    b.Property<DateTime>("OpenTimeUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<decimal>("Close")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("High")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Low")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Open")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<long?>("OpenInterest")
                        .HasColumnType("bigint");

                    b.Property<long>("Volume")
                        .HasColumnType("bigint");

                    b.HasKey("InstrumentId", "Timeframe", "OpenTimeUtc");

                    b.ToTable("Candles", null, t =>
                        {
                            t.HasCheckConstraint("CK_Candles_OpenInterest", "[OpenInterest] IS NULL OR [OpenInterest] >= 0");

                            t.HasCheckConstraint("CK_Candles_Prices", "[Low] > 0 AND [High] >= [Low] AND [Open] >= [Low] AND [Open] <= [High] AND [Close] >= [Low] AND [Close] <= [High]");

                            t.HasCheckConstraint("CK_Candles_Timeframe", "[Timeframe] IN (1, 3, 5, 15, 30, 60, 1440)");

                            t.HasCheckConstraint("CK_Candles_Volume", "[Volume] >= 0");
                        });
                });

            modelBuilder.Entity("Trading.Domain.MarketData.Instrument", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int>("LotSize")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<decimal>("TickSize")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("Exchange", "Symbol")
                        .IsUnique();

                    b.ToTable("Instruments", null, t =>
                        {
                            t.HasCheckConstraint("CK_Instruments_LotSize", "[LotSize] > 0");

                            t.HasCheckConstraint("CK_Instruments_TickSize", "[TickSize] > 0");
                        });
                });

            modelBuilder.Entity("Trading.Domain.MarketData.MarketFeedCapture", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ArtifactJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArtifactSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)")
                        .IsFixedLength();

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<DateTime>("FirstReceivedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<DateTime>("LastReceivedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("QuoteMode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("TickCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("Source", "CreatedAtUtc");

                    b.ToTable("MarketFeedCaptures", null, t =>
                        {
                            t.HasCheckConstraint("CK_MarketFeedCaptures_TickCount", "[TickCount] > 0");
                        });
                });

            modelBuilder.Entity("Trading.Domain.MarketData.OptionContract", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateOnly>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<int>("LotSize")
                        .HasColumnType("int");

                    b.Property<int>("Right")
                        .HasColumnType("int");

                    b.Property<decimal>("Strike")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("nvarchar(96)");

                    b.Property<decimal>("TickSize")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid>("UnderlyingInstrumentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Symbol")
                        .IsUnique();

                    b.HasIndex("UnderlyingInstrumentId", "ExpiryDate", "Right", "Strike")
                        .IsUnique();

                    b.ToTable("OptionContracts", null, t =>
                        {
                            t.HasCheckConstraint("CK_OptionContracts_LotSize", "[LotSize] > 0");

                            t.HasCheckConstraint("CK_OptionContracts_Right", "[Right] IN (1, 2)");

                            t.HasCheckConstraint("CK_OptionContracts_Strike", "[Strike] > 0");

                            t.HasCheckConstraint("CK_OptionContracts_TickSize", "[TickSize] > 0");
                        });
                });

            modelBuilder.Entity("Trading.Domain.MarketData.OptionQuote", b =>
                {
                    b.Property<Guid>("OptionContractId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<decimal>("Ask")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Bid")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Last")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<long>("OpenInterest")
                        .HasColumnType("bigint");

                    b.Property<long>("Volume")
                        .HasColumnType("bigint");

                    b.HasKey("OptionContractId", "TimestampUtc");

                    b.HasIndex("TimestampUtc");

                    b.ToTable("OptionQuotes", null, t =>
                        {
                            t.HasCheckConstraint("CK_OptionQuotes_OpenInterest", "[OpenInterest] >= 0");

                            t.HasCheckConstraint("CK_OptionQuotes_Prices", "[Bid] > 0 AND [Ask] >= [Bid] AND [Last] > 0");

                            t.HasCheckConstraint("CK_OptionQuotes_Volume", "[Volume] >= 0");
                        });
                });

            modelBuilder.Entity("Trading.Domain.Research.BacktestAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnalysisJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AnalysisSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)")
                        .IsFixedLength();

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("Deployment")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("InputTokens")
                        .HasColumnType("int");

                    b.Property<int>("OutputTokens")
                        .HasColumnType("int");

                    b.Property<string>("PromptSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)")
                        .IsFixedLength();

                    b.Property<string>("PromptVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ProviderResponseId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ResearchArtifactSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)")
                        .IsFixedLength();

                    b.Property<Guid>("ResearchRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ResponseModel")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("ResearchRunId", "PromptSha256", "Deployment")
                        .IsUnique();

                    b.ToTable("BacktestAnalyses", (string)null);
                });

            modelBuilder.Entity("Trading.Domain.Research.BacktestCandidate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CandidateSpecificationJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DatasetSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)")
                        .IsFixedLength();

                    b.Property<string>("NativeEngineId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("NativeEngineVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<decimal?>("NativeNetPnl")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("NativeResultSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("NativeRunJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NativeTradeCount")
                        .HasColumnType("int");

                    b.Property<Guid>("ParameterSweepId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ParametersJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.Property<string>("ResearchEvidenceSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)")
                        .IsFixedLength();

                    b.Property<string>("ResearchMetricsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ResearchScore")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<string>("SpecificationSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)")
                        .IsFixedLength();

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("StrategyId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("VerificationFailure")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTime?>("VerifiedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.HasKey("Id");

                    b.HasIndex("ParameterSweepId", "Rank")
                        .IsUnique();

                    b.HasIndex("ParameterSweepId", "SpecificationSha256")
                        .IsUnique();

                    b.ToTable("BacktestCandidates", null, t =>
                        {
                            t.HasCheckConstraint("CK_BacktestCandidates_Rank", "[Rank] > 0");

                            t.HasCheckConstraint("CK_BacktestCandidates_Status", "[Status] IN ('ResearchProposed', 'NativeVerified', 'NativeFailed')");

                            t.HasCheckConstraint("CK_BacktestCandidates_TradeCount", "[NativeTradeCount] IS NULL OR [NativeTradeCount] >= 0");
                        });
                });

            modelBuilder.Entity("Trading.Domain.Research.IssuedStrategyCertificate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CertificateJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CertificateSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)")
                        .IsFixedLength();

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<DateTime>("IssuedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("ResearchArtifactSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)")
                        .IsFixedLength();

                    b.Property<Guid>("ResearchRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("StrategyId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAtUtc");

                    b.HasIndex("ResearchRunId", "StrategyId")
                        .IsUnique();

                    b.ToTable("StrategyCertificates", (string)null);
                });

            modelBuilder.Entity("Trading.Domain.Research.NativeCandidateVerificationRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ArtifactJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArtifactSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)")
                        .IsFixedLength();

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("EngineId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("EngineVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("FailedCandidates")
                        .HasColumnType("int");

                    b.Property<Guid>("ParameterSweepId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RequestedCandidates")
                        .HasColumnType("int");

                    b.Property<int>("VerifiedCandidates")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParameterSweepId")
                        .IsUnique();

                    b.ToTable("NativeCandidateVerificationRuns", null, t =>
                        {
                            t.HasCheckConstraint("CK_NativeCandidateVerificationRuns_Counts", "[RequestedCandidates] > 0 AND [VerifiedCandidates] >= 0 AND [FailedCandidates] >= 0 AND [VerifiedCandidates] + [FailedCandidates] = [RequestedCandidates]");
                        });
                });

            modelBuilder.Entity("Trading.Domain.Research.ParameterSweep", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ArtifactJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArtifactSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)")
                        .IsFixedLength();

                    b.Property<string>("BaseSpecificationSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)")
                        .IsFixedLength();

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("DatasetSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)")
                        .IsFixedLength();

                    b.Property<int>("EvaluatedCandidates")
                        .HasColumnType("int");

                    b.Property<string>("GridSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)")
                        .IsFixedLength();

                    b.Property<bool>("NativeVerificationCompleted")
                        .HasColumnType("bit");

                    b.Property<int>("StoredCandidates")
                        .HasColumnType("int");

                    b.Property<string>("StrategyId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("WorkerId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("WorkerVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("BaseSpecificationSha256", "GridSha256", "WorkerId", "WorkerVersion")
                        .IsUnique();

                    b.ToTable("ParameterSweeps", null, t =>
                        {
                            t.HasCheckConstraint("CK_ParameterSweeps_Counts", "[EvaluatedCandidates] > 0 AND [StoredCandidates] > 0 AND [StoredCandidates] <= [EvaluatedCandidates]");
                        });
                });

            modelBuilder.Entity("Trading.Domain.Research.ResearchRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ArtifactJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArtifactSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)")
                        .IsFixedLength();

                    b.Property<string>("CalendarId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ConfigurationSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)")
                        .IsFixedLength();

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("DataSource")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("DataVersion")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("DatasetSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)")
                        .IsFixedLength();

                    b.Property<DateTime>("FromUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<Guid>("InstrumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SourceRevision")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("Timeframe")
                        .HasColumnType("int");

                    b.Property<DateTime>("ToUtc")
                        .HasColumnType("datetime2(7)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("DatasetSha256", "ConfigurationSha256", "SourceRevision")
                        .IsUnique();

                    b.HasIndex("InstrumentId", "Timeframe", "FromUtc", "ToUtc");

                    b.ToTable("ResearchRuns", (string)null);
                });

            modelBuilder.Entity("Trading.Domain.Execution.ControlledAutomationAuthorization", b =>
                {
                    b.HasOne("Trading.Domain.Execution.LiveOrderRecord", null)
                        .WithOne()
                        .HasForeignKey("Trading.Domain.Execution.ControlledAutomationAuthorization", "RelatedLiveOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Trading.Domain.Execution.LiveOrderRecord", b =>
                {
                    b.HasOne("Trading.Domain.Research.IssuedStrategyCertificate", null)
                        .WithMany()
                        .HasForeignKey("StrategyCertificateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Trading.Domain.Execution.PaperTradingSession", b =>
                {
                    b.HasOne("Trading.Domain.MarketData.MarketFeedCapture", null)
                        .WithMany()
                        .HasForeignKey("MarketFeedCaptureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Trading.Domain.Research.IssuedStrategyCertificate", null)
                        .WithMany()
                        .HasForeignKey("StrategyCertificateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Trading.Domain.MarketData.Candle", b =>
                {
                    b.HasOne("Trading.Domain.MarketData.Instrument", null)
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Trading.Domain.MarketData.OptionContract", b =>
                {
                    b.HasOne("Trading.Domain.MarketData.Instrument", null)
                        .WithMany()
                        .HasForeignKey("UnderlyingInstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Trading.Domain.MarketData.OptionQuote", b =>
                {
                    b.HasOne("Trading.Domain.MarketData.OptionContract", null)
                        .WithMany()
                        .HasForeignKey("OptionContractId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Trading.Domain.Research.BacktestAnalysis", b =>
                {
                    b.HasOne("Trading.Domain.Research.ResearchRun", null)
                        .WithMany()
                        .HasForeignKey("ResearchRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Trading.Domain.Research.BacktestCandidate", b =>
                {
                    b.HasOne("Trading.Domain.Research.ParameterSweep", null)
                        .WithMany()
                        .HasForeignKey("ParameterSweepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Trading.Domain.Research.IssuedStrategyCertificate", b =>
                {
                    b.HasOne("Trading.Domain.Research.ResearchRun", null)
                        .WithMany()
                        .HasForeignKey("ResearchRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Trading.Domain.Research.NativeCandidateVerificationRun", b =>
                {
                    b.HasOne("Trading.Domain.Research.ParameterSweep", null)
                        .WithMany()
                        .HasForeignKey("ParameterSweepId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Trading.Domain.Research.ResearchRun", b =>
                {
                    b.HasOne("Trading.Domain.MarketData.Instrument", null)
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
