// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Trading.Infrastructure.Persistence;

#nullable disable

namespace Trading.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TradingDbContext))]
    [Migration("20260915124000_M16ResearchIntegrity")]
    partial class M16ResearchIntegrity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Trading.Domain.MarketData.Candle", b =>
                {
                    b.Property<Guid>("InstrumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Timeframe")
                        .HasColumnType("int");

                    b.Property<DateTime>("OpenTimeUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<decimal>("Close")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("High")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Low")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Open")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<long?>("OpenInterest")
                        .HasColumnType("bigint");

                    b.Property<long>("Volume")
                        .HasColumnType("bigint");

                    b.HasKey("InstrumentId", "Timeframe", "OpenTimeUtc");

                    b.ToTable("Candles", null, t =>
                        {
                            t.HasCheckConstraint("CK_Candles_OpenInterest", "[OpenInterest] IS NULL OR [OpenInterest] >= 0");

                            t.HasCheckConstraint("CK_Candles_Prices", "[Low] > 0 AND [High] >= [Low] AND [Open] >= [Low] AND [Open] <= [High] AND [Close] >= [Low] AND [Close] <= [High]");

                            t.HasCheckConstraint("CK_Candles_Timeframe", "[Timeframe] IN (1, 3, 5, 15, 30, 60, 1440)");

                            t.HasCheckConstraint("CK_Candles_Volume", "[Volume] >= 0");
                        });
                });

            modelBuilder.Entity("Trading.Domain.MarketData.Instrument", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int>("LotSize")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<decimal>("TickSize")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("Exchange", "Symbol")
                        .IsUnique();

                    b.ToTable("Instruments", null, t =>
                        {
                            t.HasCheckConstraint("CK_Instruments_LotSize", "[LotSize] > 0");

                            t.HasCheckConstraint("CK_Instruments_TickSize", "[TickSize] > 0");
                        });
                });

            modelBuilder.Entity("Trading.Domain.Research.ResearchRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ArtifactJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArtifactSha256")
                        .IsRequired()
                        .IsFixedLength()
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)");

                    b.Property<string>("CalendarId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ConfigurationSha256")
                        .IsRequired()
                        .IsFixedLength()
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("DatasetSha256")
                        .IsRequired()
                        .IsFixedLength()
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)");

                    b.Property<string>("DataSource")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("DataVersion")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("FromUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<Guid>("InstrumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SourceRevision")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("Timeframe")
                        .HasColumnType("int");

                    b.Property<DateTime>("ToUtc")
                        .HasColumnType("datetime2(7)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("DatasetSha256", "ConfigurationSha256", "SourceRevision")
                        .IsUnique();

                    b.HasIndex("InstrumentId", "Timeframe", "FromUtc", "ToUtc");

                    b.ToTable("ResearchRuns");
                });

            modelBuilder.Entity("Trading.Domain.MarketData.Candle", b =>
                {
                    b.HasOne("Trading.Domain.MarketData.Instrument", null)
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Trading.Domain.Research.ResearchRun", b =>
                {
                    b.HasOne("Trading.Domain.MarketData.Instrument", null)
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
