// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Trading.Infrastructure.Persistence;

#nullable disable

namespace Trading.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TradingDbContext))]
    [Migration("20260915220000_M21ZerodhaMarketFeeds")]
    partial class M21ZerodhaMarketFeeds
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Trading.Domain.MarketData.Candle", b =>
                {
                    b.Property<Guid>("InstrumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Timeframe")
                        .HasColumnType("int");

                    b.Property<DateTime>("OpenTimeUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<decimal>("Close")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("High")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Low")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Open")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<long?>("OpenInterest")
                        .HasColumnType("bigint");

                    b.Property<long>("Volume")
                        .HasColumnType("bigint");

                    b.HasKey("InstrumentId", "Timeframe", "OpenTimeUtc");

                    b.ToTable("Candles", null, t =>
                        {
                            t.HasCheckConstraint("CK_Candles_OpenInterest", "[OpenInterest] IS NULL OR [OpenInterest] >= 0");

                            t.HasCheckConstraint("CK_Candles_Prices", "[Low] > 0 AND [High] >= [Low] AND [Open] >= [Low] AND [Open] <= [High] AND [Close] >= [Low] AND [Close] <= [High]");

                            t.HasCheckConstraint("CK_Candles_Timeframe", "[Timeframe] IN (1, 3, 5, 15, 30, 60, 1440)");

                            t.HasCheckConstraint("CK_Candles_Volume", "[Volume] >= 0");
                        });
                });

            modelBuilder.Entity("Trading.Domain.MarketData.Instrument", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int>("LotSize")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<decimal>("TickSize")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("Exchange", "Symbol")
                        .IsUnique();

                    b.ToTable("Instruments", null, t =>
                        {
                            t.HasCheckConstraint("CK_Instruments_LotSize", "[LotSize] > 0");

                            t.HasCheckConstraint("CK_Instruments_TickSize", "[TickSize] > 0");
                        });
                });

            modelBuilder.Entity("Trading.Domain.MarketData.OptionContract", b =>
                {
                    b.Property<Guid>("Id").HasColumnType("uniqueidentifier");
                    b.Property<string>("Exchange").IsRequired().HasMaxLength(16).HasColumnType("nvarchar(16)");
                    b.Property<DateOnly>("ExpiryDate").HasColumnType("date");
                    b.Property<int>("LotSize").HasColumnType("int");
                    b.Property<int>("Right").HasColumnType("int");
                    b.Property<decimal>("Strike").HasPrecision(18, 4).HasColumnType("decimal(18,4)");
                    b.Property<string>("Symbol").IsRequired().HasMaxLength(96).HasColumnType("nvarchar(96)");
                    b.Property<decimal>("TickSize").HasPrecision(18, 4).HasColumnType("decimal(18,4)");
                    b.Property<Guid>("UnderlyingInstrumentId").HasColumnType("uniqueidentifier");
                    b.HasKey("Id");
                    b.HasIndex("Symbol").IsUnique();
                    b.HasIndex("UnderlyingInstrumentId", "ExpiryDate", "Right", "Strike").IsUnique();
                    b.ToTable("OptionContracts", null, t =>
                        {
                            t.HasCheckConstraint("CK_OptionContracts_LotSize", "[LotSize] > 0");
                            t.HasCheckConstraint("CK_OptionContracts_Right", "[Right] IN (1, 2)");
                            t.HasCheckConstraint("CK_OptionContracts_Strike", "[Strike] > 0");
                            t.HasCheckConstraint("CK_OptionContracts_TickSize", "[TickSize] > 0");
                        });
                });

            modelBuilder.Entity("Trading.Domain.MarketData.OptionQuote", b =>
                {
                    b.Property<Guid>("OptionContractId").HasColumnType("uniqueidentifier");
                    b.Property<DateTime>("TimestampUtc").HasColumnType("datetime2(7)");
                    b.Property<decimal>("Ask").HasPrecision(18, 4).HasColumnType("decimal(18,4)");
                    b.Property<decimal>("Bid").HasPrecision(18, 4).HasColumnType("decimal(18,4)");
                    b.Property<decimal>("Last").HasPrecision(18, 4).HasColumnType("decimal(18,4)");
                    b.Property<long>("OpenInterest").HasColumnType("bigint");
                    b.Property<long>("Volume").HasColumnType("bigint");
                    b.HasKey("OptionContractId", "TimestampUtc");
                    b.HasIndex("TimestampUtc");
                    b.ToTable("OptionQuotes", null, t =>
                        {
                            t.HasCheckConstraint("CK_OptionQuotes_OpenInterest", "[OpenInterest] >= 0");
                            t.HasCheckConstraint("CK_OptionQuotes_Prices", "[Bid] > 0 AND [Ask] >= [Bid] AND [Last] > 0");
                            t.HasCheckConstraint("CK_OptionQuotes_Volume", "[Volume] >= 0");
                        });
                });

            modelBuilder.Entity("Trading.Domain.MarketData.MarketFeedCapture", b =>
                {
                    b.Property<Guid>("Id").HasColumnType("uniqueidentifier");
                    b.Property<string>("ArtifactJson").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("ArtifactSha256").IsRequired().IsFixedLength().HasMaxLength(64).HasColumnType("nchar(64)");
                    b.Property<DateTime>("CreatedAtUtc").HasColumnType("datetime2(7)");
                    b.Property<DateTime>("FirstReceivedAtUtc").HasColumnType("datetime2(7)");
                    b.Property<DateTime>("LastReceivedAtUtc").HasColumnType("datetime2(7)");
                    b.Property<string>("QuoteMode").IsRequired().HasMaxLength(16).HasColumnType("nvarchar(16)");
                    b.Property<string>("Source").IsRequired().HasMaxLength(32).HasColumnType("nvarchar(32)");
                    b.Property<int>("TickCount").HasColumnType("int");
                    b.HasKey("Id");
                    b.HasIndex("CreatedAtUtc");
                    b.HasIndex("Source", "CreatedAtUtc");
                    b.ToTable("MarketFeedCaptures", null, t =>
                        {
                            t.HasCheckConstraint("CK_MarketFeedCaptures_TickCount", "[TickCount] > 0");
                        });
                });

            modelBuilder.Entity("Trading.Domain.Research.ResearchRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ArtifactJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArtifactSha256")
                        .IsRequired()
                        .IsFixedLength()
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)");

                    b.Property<string>("CalendarId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ConfigurationSha256")
                        .IsRequired()
                        .IsFixedLength()
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("DatasetSha256")
                        .IsRequired()
                        .IsFixedLength()
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)");

                    b.Property<string>("DataSource")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("DataVersion")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("FromUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<Guid>("InstrumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SourceRevision")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("Timeframe")
                        .HasColumnType("int");

                    b.Property<DateTime>("ToUtc")
                        .HasColumnType("datetime2(7)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("DatasetSha256", "ConfigurationSha256", "SourceRevision")
                        .IsUnique();

                    b.HasIndex("InstrumentId", "Timeframe", "FromUtc", "ToUtc");

                    b.ToTable("ResearchRuns");
                });

            modelBuilder.Entity("Trading.Domain.Research.BacktestAnalysis", b =>
                {
                    b.Property<Guid>("Id").HasColumnType("uniqueidentifier");
                    b.Property<string>("AnalysisJson").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("AnalysisSha256").IsRequired().IsFixedLength().HasMaxLength(64).HasColumnType("nchar(64)");
                    b.Property<DateTime>("CreatedAtUtc").HasColumnType("datetime2(7)");
                    b.Property<string>("Deployment").IsRequired().HasMaxLength(128).HasColumnType("nvarchar(128)");
                    b.Property<int>("InputTokens").HasColumnType("int");
                    b.Property<int>("OutputTokens").HasColumnType("int");
                    b.Property<string>("PromptSha256").IsRequired().IsFixedLength().HasMaxLength(64).HasColumnType("nchar(64)");
                    b.Property<string>("PromptVersion").IsRequired().HasMaxLength(64).HasColumnType("nvarchar(64)");
                    b.Property<string>("ProviderResponseId").IsRequired().HasMaxLength(128).HasColumnType("nvarchar(128)");
                    b.Property<Guid>("ResearchRunId").HasColumnType("uniqueidentifier");
                    b.Property<string>("ResearchArtifactSha256").IsRequired().IsFixedLength().HasMaxLength(64).HasColumnType("nchar(64)");
                    b.Property<string>("ResponseModel").IsRequired().HasMaxLength(128).HasColumnType("nvarchar(128)");
                    b.HasKey("Id");
                    b.HasIndex("CreatedAtUtc");
                    b.HasIndex("ResearchRunId", "PromptSha256", "Deployment").IsUnique();
                    b.ToTable("BacktestAnalyses");
                });

            modelBuilder.Entity("Trading.Domain.Research.IssuedStrategyCertificate", b =>
                {
                    b.Property<Guid>("Id").HasColumnType("uniqueidentifier");
                    b.Property<string>("CertificateJson").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("CertificateSha256").IsRequired().IsFixedLength().HasMaxLength(64).HasColumnType("nchar(64)");
                    b.Property<DateTime>("ExpiresAtUtc").HasColumnType("datetime2(7)");
                    b.Property<DateTime>("IssuedAtUtc").HasColumnType("datetime2(7)");
                    b.Property<Guid>("ResearchRunId").HasColumnType("uniqueidentifier");
                    b.Property<string>("ResearchArtifactSha256").IsRequired().IsFixedLength().HasMaxLength(64).HasColumnType("nchar(64)");
                    b.Property<string>("Status").IsRequired().HasMaxLength(32).HasColumnType("nvarchar(32)");
                    b.Property<string>("StrategyId").IsRequired().HasMaxLength(128).HasColumnType("nvarchar(128)");
                    b.HasKey("Id");
                    b.HasIndex("ExpiresAtUtc");
                    b.HasIndex("ResearchRunId", "StrategyId").IsUnique();
                    b.ToTable("StrategyCertificates");
                });

            modelBuilder.Entity("Trading.Domain.Research.BacktestAnalysis", b =>
                {
                    b.HasOne("Trading.Domain.Research.ResearchRun", null)
                        .WithMany()
                        .HasForeignKey("ResearchRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Trading.Domain.MarketData.Candle", b =>
                {
                    b.HasOne("Trading.Domain.MarketData.Instrument", null)
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Trading.Domain.Research.ResearchRun", b =>
                {
                    b.HasOne("Trading.Domain.MarketData.Instrument", null)
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Trading.Domain.Research.IssuedStrategyCertificate", b =>
                {
                    b.HasOne("Trading.Domain.Research.ResearchRun", null)
                        .WithMany()
                        .HasForeignKey("ResearchRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Trading.Domain.MarketData.OptionContract", b =>
                {
                    b.HasOne("Trading.Domain.MarketData.Instrument", null)
                        .WithMany()
                        .HasForeignKey("UnderlyingInstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Trading.Domain.MarketData.OptionQuote", b =>
                {
                    b.HasOne("Trading.Domain.MarketData.OptionContract", null)
                        .WithMany()
                        .HasForeignKey("OptionContractId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
