<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../Trading.Application/Trading.Application.csproj" />
    <ProjectReference Include="../Trading.Strategies/Trading.Strategies.csproj" />
    <ProjectReference Include="../Trading.MarketData/Trading.MarketData.csproj" />
    <ProjectReference Include="../Trading.Risk/Trading.Risk.csproj" />
  </ItemGroup>
</Project>
